version: "3.7"
services:
  ecs-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_SDK_LOAD_CONFIG: 1
      AWS_PROFILE: "mwbops"
    volumes:
      - "~/.aws/:/root/.aws/"
    tty: true